# Generated by Django 3.2.16 on 2023-05-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='votaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
