# Generated by Django 3.2.16 on 2023-05-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscriptionTypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscriptiontypes',
            name='footer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suscriptiontypes',
            name='productScreen',
            field=models.BooleanField(default=False),
        ),
    ]
